README.md, bin/strap.sh, web/app.rb
Makes a few fixes based on user feedback.
=> Fix some User Feedback

README.md
Just found out svgs are supported for the deploy button, looks much better on retina :grin:
=> Use svg instead of png for heroku deploy button

README.md, bin/strap.sh
Enable a few more security features. CC @joewilliams
Closes #8.
=> Improve security

.travis.yml
Only use 2 jobs instead of 3 and use latest Xcode version for 10.9.
=> Improve Travis YML configuration.

.travis.yml
Now that Travis provides this image.
=> travis.yml: use OS X 10.11.

bin/strap.sh
Change these permissions again based on Homebrew support for El Capitan.
=> Tweak Homebrew permissions.

bin/strap.sh
Improve debugging by pointing to `--debug` and pointing out the step that failed.
=> Output message on failure.

README.md, app.json, bin/strap.sh, web/app.rb
Also:
- app.json: add missing full-stop.
- Describe WEB_CONCURRENCY defaults.
=> Allow customising the issues submission URL

.gitignore, .travis.yml, README.md, bin/strap.sh, script/bootstrap, script/cibuild, script/server, web/app.rb
Add various helper scripts and make CI start the server and download from it. Also, fix the `sudo` wait script handling and ensure HTTPS is always used in production.
Closes #33.
=> Various fixes

bin/strap.sh
This is the consistent place used by various projects.
=> Set GitHub user.

bin/strap.sh
Don't need an extra file for this.
=> strap.sh: pass Brewfile over STDIN

bin/strap.sh
Reverts mikemcquaid/strap#46 due to issues described there.
=> Revert "strap.sh: pass Brewfile over STDIN"

bin/strap.sh, script/cibuild
Fix shellcheck warnings and add additional comments.
=> Fix warnings

README.md, app.json, web/app.rb
Allow customizing instructions for users to follow before installing Strap.
=> Add STRAP_BEFORE_INSTALL variable.

.travis.yml, bin/strap.sh
Also ensure the `homebrew-core` tap is tapped.
=> Use new Homebrew repository.

bin/strap.sh
Reverts mikemcquaid/strap#60. It doesn't fix the bug.
=> Revert "Check Homebrew has migrated to Homebrew/brew."

bin/strap.sh
Previously it was missing a line break before asking for the password.
=> strap.sh: improve FileVault message output.

bin/strap.sh
seems to work fine for me on a fresh install.
=> Allow macOS 10.12

bin/strap.sh
This matches the upstream Homebrew installer changes doing the same (https://github.com/Homebrew/install/pull/60). Don't move people's Homebrew installations around, though; respect their previous location and leave any migration to `brew update`.
CC @mistydemeo just FYI that this is happening.
=> Change default HOMEBREW_REPOSITORY location.

bin/strap.sh
=> Run bundle check before running bundle in case bundle has already been run

README.md
- Tweak wording to make writing clearer and firmer
- Explain the motivation
- Elaborate on features that won't be added
- Point to new Heroku URL
=> README: general cleanup

bin/strap.sh
=> Added macOS High Sierra as a supported platform

Gemfile, Gemfile.lock
- Improve ordering
- Update Ruby version
=> Gemfile: various cleanups.

README.md, app.json, bin/strap.sh, web/app.rb, web/views/root.erb
Strap is looking a bit stale and very Bootstrap 3. Update it to Bootstrap 4, do some basic theming and add a small link to my own site.
=> Refresh branding

bin/strap.sh, web/app.rb
Also, clean things up a bit while we’re here.
Fixes #158
=> Escape single quote characters

web/app.rb
Skip over them rather than trying to replace them.
Fixes #173.
=> web/app: handle nil/empty environment variables.

README.md
As Strap is now using it for CI.
=> README: use Azure pipelines badge.

Gemfile.lock, azure-pipelines.yml
Use latest macOS/Xcode settings and `Gemfile.lock`.
=> Update Azure Pipelines

Gemfile.lock
=> Gemfile.lock: update Ruby version.

README.md, bin/strap.sh
I've discovered that I have some steps that require formulas from from the homebrew-brewfile repo, local Brewfile, custom brew tap or custom brew command. As such I'd find it helpful to run a different script at the very end of strap to run those steps.
=> Add postinstall step

bin/strap.sh
This adds support for the 10.15 beta.
=> strap.sh: add 10.15

Gemfile.lock, script/cibuild
Keep forgetting to do this so add a test as it breaks Heroku deploys.
=> Bump Ruby version in Gemfile and add test

web/app.rb
Enable the Rack::Protection settings that make sense for this app.
=> web/app: use Rack::Protection.

README.md, app.json, web/app.rb
I've disabled issues on my repository so tell users of my/the default installation to try to figure things out for themselves.
=> STRAP_ISSUES_URL: default to no URL.

README.md
=> README: fix Markdown linter warnings.

README.md
Resolves some user confusion.
Closes #327.
=> README: clarify script/* run conditions.

.github/workflows/tests.yml, script/cibuild
Let's get this working before it is released.
=> workflows/tests: test Big Sur.

web/app.rb
=> Use POST for OmniAuth.

.github/workflows/tests.yml, .rubocop.yml, Gemfile, Gemfile.lock, Guardfile, config.ru, script/bootstrap, script/cibuild, web/app.rb, web/unicorn.rb
Add RuboCop, fix all violations and run it in CI.
=> Add RuboCop

Dockerfile, script/cibuild
This can be used to run locally, for CI, etc. ~~The second commit I've attached updates `cibuild` to use Docker, but I can remove that from this PR if you prefer.~~ Reverted the second commit, since CI runs under macOS and Actions doesn't provide Docker on macOS runners.
=> Add a simple Dockerfile

bin/strap.sh
As titled, I copied the logic from homebrew installation script.
=> Support ARM macOS

.github/workflows/tests.yml, bin/strap.sh
Tweak the output when using `STRAP_CI`.
=> bin/strap.sh: improve CI output.

.github/workflows/tests.yml
=> workflows/tests: use new Ruby action.

web/views/root.erb
Use github.io which still works.
=> root.erb: fix fork link.

.github/workflows/tests.yml
It's currently trying to switch to one that doesn't exist.
=> workflows/tests: fix Xcode handling.

web/app.rb
=> web/app: clarify credentials usage.

bin/strap.sh
This is the only way I could get it work in Monterey 🤷
=> Sudo all the default writes in security

.github/workflows/tests.yml
Use some new features and cache Bundler.
=> Cleanup GitHub Actions

.github/dependabot.yml
This gives me a consistent time when I can apply updates. Also, allow VS Code to auto format the YAML.
=> Set Dependabot time

.github/workflows/tests.yml
Don't try to login when we don't have tokens.
=> workflows/tests: fix CI from forks.

web/unicorn.rb
This is recommended in the Sinatra docs.
=> web/unicorn: increase session secret size.

.github/dependabot.yml
This should help keep abreast of any needed updates.
=> dependabot: update Docker.

Dockerfile
Make sure we get any lovely security updates that haven't been applied upstream yet.
=> Dockerfile: run `apt-get upgrade`.

.github/codeql.yml, .github/workflows/codeql.yml
=> Add CodeQL support

web/views/root.erb
=> web/views/root: request sponsorship.

.rubocop.yml, bin/strap.sh, script/style
Allow VSCode to auto-format all files in this repository.
=> VSCode auto-formatting

web/views/root.erb
=> Note I've left GitHub.

web/views/root.erb
=> root.erb: shorten wording.

.github/workflows/tests.yml, Dockerfile, script/style
This should avoid duplication between this and the `.ruby-version`.
=> Dockerfile: use RUBY_VERSION argument.

bin/strap.sh
This now survives system updates.
Reference: https://sixcolors.com/post/2023/08/in-macos-sonoma-touch-id-for-sudo-can-survive-updates/
=> bin/strap.sh: use Sonoma's sudo_local instead of sudo.

.github/workflows/codeql.yml, .github/workflows/tests.yml, README.md
- Change `master` references
- Push `main`, `master` and `latest` Docker tags
=> Make `main` the default branch

script/tests
The case has changed here but the header is still present.
=> script/tests: fix header detection.

Gemfile, Gemfile.lock
This stops Unicorn from whining every time on launch.
=> Use faraday-retry

.github/workflows/tests.yml
It's the latest and is much faster.
=> github/workflows: use macos-14 worker.

.github/workflows/tests.yml
This should fix the issues pushing on `main`.
=> workflows/tests: login to DigitalOcean using `doctl`.

script/server
This should fix the deployment failures.
=> script/server: use /bin/sh for Alpine Linux.
