- .travis.yml
- bin/strap.sh
Even although Strap is hardcoded to use `/bin/bash` I think it's a bit nicer to not rely on Bashisms so people can extract(/copy-paste) bits elsewhere and have them work regardless of their shell of choice.
> Check for (and don't use) Bashisms.

- bin/strap.sh
- web/app.rb
- Use GitHub username instead of email
- Use `git config` instead of `git config --global` in case any configuration variables are set outside the global configuration file.
- Still try to setup credential helper even if the `user.email` has already been set.
> Improve Git credential handling.

- bin/strap.sh
Sometimes people may have `/usr/local` permissions that require a bit more manual coaxing to work.
CC @dice
> strap.sh: fix Homebrew permission issues.

- bin/strap.sh
Use a LaunchDaemon plist loaded with `launchctl`. Otherwise it won’t be re-enabled on boot. CC @josh
> Load pf on every boot

- bin/strap.sh
Stop e.g. `zsh` from complaining about the group writable permissions.
> Tweak Homebrew permissions

- README.md
- bin/strap.sh
They don’t rely on other operations having run and it’s nice to have them enabled even if the script fails later and people give up on it.
Also: note idempotency.
> Run security operations first.

- bin/strap.sh
Previously there could be leftover `dev.strap` or `dev.github` lines which, when duplicated, would cause issues. Also ensure that the `launchctl` property list is unloaded before we reload it.
> Ensure that PF anchors are always applied cleanly.

- bin/strap.sh
Xcode may have been updated in which case the license may need to be accepted again.
@blackjid: does this do what you were thinking?
Closes #30.
> Accept Xcode license again after OS X updates.

- README.md
- bin/strap.sh
The idea is to add support for custom brew packages.
It should download the `Brewfile` from users `homebrew-brewfile` and then run `brew bundle --global`
I still think that is a good place for organization defaults.. but maybe we can discuss that in a separe issue.
closes #21
> Gets `.Brewfile` from github and run brew bundle

- bin/strap.sh
Ensures that users won't have to reenter their `sudo` password periodically if a command takes a long time to run.
> Keep sudo timestamp updated until Strap exits.

- bin/strap.sh
CC @technicalpickles
Closes #33.
> Use fully-qualified path for `--sudo-wait` option.

- bin/strap.sh
If the user has disabled this for whatever reason then this will ensure it's enabled again.
> Make pf launchd service be always loaded, enabled.

- bin/strap.sh
If no `push.default` setting exists, git outputs a massive warning message on each `git push` because the defaults have changed since git 1.x. This explicitly opts into git 2.x behavior which is the default.
The default git version on El Capitan is 2.4, while Homebrew installs 2.6.
I feel that this belongs to Strap because it's supposed to get you ready for `git push`in'. Well, it does, but you also get a massive warning on stderr, which doesn't feel very nice:
```
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:
git config --global push.default matching
To squelch this message and adopt the new behavior now, use:
git config --global push.default simple
When …
```
> Squelch git 2.x warning message on `git push`

- bin/strap.sh
Unfortunately `sudo -v` does not work as documented and doesn't update the timestamp if it's in an already-running `sudo` session.
CC @blackjid
Closes #41.
> Fix sudo-wait.

- bin/strap.sh
If you want to run strap again, but you revoked your token and had to reauthorized strap, the new one was not being setup in the git configure step.
This will check if the strap.sh STRAP_GITHUB_USER or STRAP_GITHUB_TOKEN have changed, if so, it will erase the old ones and store the new ones.
> reset github keychain credentials if they changed

- bin/strap.sh
They are autoinstalled by Homebrew now so these lines are no longer needed.
CC @jdpace
> strap.sh: remove bundle/cask installs.

- bin/strap.sh
Wait for the network connections to come up to avoid the `DIOCADDRULE` error and manually start up the firewall.
> Ensure pf rules (and firewall) are loaded.

- bin/strap.sh
It's sometimes confusing for users as they think they have to do something when they actually don't.
CC @amosie
> Don't recommend brew/cask install.

- bin/strap.sh
Use the GitHub API to read the homebrew-brewfile/Brewfile to to allow access to private repositories.
> Read homebrew-brewfile/Brewfile from API

- bin/strap.sh
Even if Xcode is installed. Also, check for the presence of a header they install to double-check that they are definitely installed correctly (as it seems OS X updates could mess up with the previous check) and fall back to `xcode-select --install` when needed.
CC @jgkite
> Always install the Xcode CLT.

- bin/strap.sh
If it has not be sure to `git fetch` and `git reset` accordingly so it is on the correct upstream repository and branch.
> Check Homebrew has migrated to Homebrew/brew.

- bin/strap.sh
`brew update` is fast/smart enough to not redo the slow fetch now and this avoids edge cases pre/post-Homebrew repository migration.
> Fetch Homebrew unconditionally.

- bin/strap.sh
Be willing to update shallow repositories and handle remote history rewriting (i.e. the Homebrew repository migration).
> Try harder to fetch Homebrew.

- bin/strap.sh
- Don't need to create the global cache any more; it now defaults to being under `~`.
- Don't fetch a refspec as it's unneeded and produces weird results on occasion (e.g. deleting the existing one).
> Fix some Homebrew bugs.

- bin/strap.sh
This prevents overwriting Git configuration in the the non-default location.
> Only set GitHub user if not already set.

- bin/strap.sh
Strap is optimised for single user machines and making this group writable makes ZSH complain.
> Don't make Homebrew prefix group writable.

- README.md
Looks like the Travis CI badge and link to the project were broken, since the URL is case sensitive. This PR fixes those links to restore the shiny green badge. ✨
> fix broken Travis CI urls

- README.md
- bin/strap.sh
This used `pf` rules but, in practice, has unfortunately proved far too unreliable to depend on. Instead GitHub is going to lean into using `launch_socket_server` in Homebrew with the default plist installed as of https://github.com/Homebrew/homebrew-core/pull/2773 (version `1.0.0_1`) to provide the proxying.
> Remove port 80/443 to 8080/8443 forwarding.

- .travis.yml
The `osx_image: osx10.11` image name was not meant to be a long term supported thing, we've transition to just `xcodeX.x` based names, see https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
Any builds on Travis will, unfortunately, fail, as we didn't realize this tag name was in use in the _wild_ anymore, until you merge in this change.
Thanks for understanding.
> Remove osx10.11 image name as it's no longer supported

- bin/strap.sh
If someone has intentionally unshallowed Homebrew this will reshallow it but if it's still shallow this will still do a shallow fetch.
> Don't shallow fetch Homebrew if already installed.

- bin/strap.sh
Rather than just checking for the `--global` result.
> Only set GitHub user if unset in all gitconfig.

- README.md
- bin/strap.sh
If users have a dotfiles repository on GitHub then fetch it and install them locally.
Fixes #40. CC @johndbritton @AlJohri for testing, review and thoughts on the approach, code and docs.
> Fetch user dotfiles from GitHub.

- bin/strap.sh
Use `git ls-remote` instead of the GitHub API for the dotfiles and homebrew-brewfile repository checks. This means a GitHub API token is not needed and instead it relies on the authentication that would be used on for cloning the repository.
Additionally, try `script/bootstrap` if `script/setup` doesn't exist and still clone the repository to the right location even if neither do.
CC @johndbritton for 💭
> `git ls-remote` dotfiles/homebrew-brewfile checks.

- script/cibuild
As this sometimes seems to timeout on Travis CI.
> cibuild: wait longer for server to come up.

- web/app.rb
Following up on the tweak to the README for #85, this adds a user-visible caveat in the webapp.
> App: add user-visible note about organization auth

- web/app.rb
Fix to stop security warning in chrome for non secure image
> Don't force fork badge to use http://

- README.md
- bin/strap.sh
It has been deprecated for a while and the migration to `homebrew/core` is now complete.
> Remove homebrew/versions tap

- .travis.yml
This avoids having to hardcode this version in another place.
> travis.yml: use .ruby-version.

- bin/strap.sh
- only try to `chown` `/usr/local` as the `root` user (not random Homebrew prefixes).
- allow this `chown` to fail on e.g. Sierra and above where even `root` doesn't have permissions sometimes to modify `/usr/local`'s permissions.
> Tweak HOMEBREW_PREFIX chown behaviour

- bin/strap.sh
If you re-ran strap it would never update the Brewfile repo because the test for an existing Brewfile `! [ -f "$HOME/.Brewfile" ]` would always catch the symlink that is created on the first run. In bash `-f` tests for _regular files_ which includes symlinks.
This patch improves that set of conditions to include those where strap has already created a symlink.
I've tested this locally and it works great and my repo now gets a pull before strap runs `brew bundle`
> Improve test for existing Brewfile

- bin/strap.sh
Use a function rather than a subshell to avoid overhead.
> bin/strap.sh: fix shellcheck warning.

- web/app.rb
I've been seeing errors like this when `/auth/github/callback`:
```
2018-07-11T16:48:04.574786+00:00 app[web.1]: Warning! Rack::Session::Cookie data size exceeds 4K.
2018-07-11T16:48:04.574857+00:00 app[web.1]: Warning! Rack::Session::Cookie failed to save session. Content dropped.
```
That means that auth is never saved, so I'm never able to be authenticated, and thus get tokens.
There is a lot of information that comes from omniauth. In practice,
strap only uses:
- email
- nickname
- name
- token
Nothing from the 'extra' key is used, so we can create a new hash that
just has 'info' and 'credentials'
> Store a lot less on the session to avoid hitting 4k limit for some user profiles

- bin/strap.sh
Parentheses are the plist format's array literal. Any text contained within a set of parentheses is assumed to be an array, not part of the text. This can be fixed by encasing the entire text in single quotes, and escaping any single quotes within the text.
It looks like this is the only `defaults write` call which passes user-supplied text, so everything else should be fine.
> strap.sh: single quote strings that may contain parens

- bin/strap.sh
Use tail to select last item when there are multiple results (matches Homebrew behavior).
Resolves #156
> strap.sh: Change CLT package selection

- bin/strap.sh
Since macOS 10.14 is coming up, this adds support for it. A couple of changes:
1. Explicitly recognize 10.14 as a valid OS.
2. Remove the hardcoded `iconv.h` check, since headers are no longer installed at that location.
> Enable running on macOS 10.14

- bin/strap.sh
Addresses #183.
I believe that this should solve the original issue in #152 without showing double-quoted strings on the lock screen.
```bash
STRAP_GIT_NAME="My (awes'ome) Nåme"
STRAP_GIT_EMAIL="ñøbo'dy'@t'he(internet).com"
if [ -n "$STRAP_GIT_NAME" ] && [ -n "$STRAP_GIT_EMAIL" ]; then
sudo defaults write /Library/Preferences/com.apple.loginwindow \
LoginwindowText \
"'Found this computer? Please contact $(escape "$STRAP_GIT_NAME") at $(escape "$STRAP_GIT_EMAIL").'"
fi
```
```bash
/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
```
> Improve string escaping for LoginWindowText

- bin/strap.sh
For users without apostrophes or parens in their `STRAP_GIT_NAME` or `STRAP_GIT_EMAIL`, single quoting the defaults string ends up displaying the quotes. To avoid this issue, if those characters are not present we should store the string without quotes.
In #187 I did not account for my own use case 😅
> Only single-quote login text if parens are present in LOGIN_TEXT

- bin/strap.sh
- `git fetch` always non-shallow (as Homebrew does now)
- homebrew/cask is the cask tap now
> bin/strap.sh: various fixes.

- bin/strap.sh
It is no longer used. Cleverly spotted by @ricardobcl in https://github.com/MikeMcQuaid/strap/pull/200/files#r243352416. Nice work and thanks :heart:.
> bin/strap.sh: remove HOMEBREW_EXISTING variable.

- azure-pipelines.yml
> azure-pipelines: use one job syntax.

- bin/strap.sh
This is a simple change to prevent the machine sleeping whilst the strap script is running. Hopefully simple enough to pass the litmus test in #124? It makes use of the macOS built in CLI tool `caffeinate`.
The command I've selected here uses `-i` (prevent system from idle sleeping), `-d` (prevent display from sleeping and `-w` (wait for process with PID to exit - in this case the PID of the bash shell running the script). 
There is an argument for removing `-d` but I prefer to see progress so left it in.
> Avoid machine sleeping whilst running strap

- bin/strap.sh
The quotes around `$CUSTOM_BREW_COMMAND` caused us issues. i.e.
```
➜  brew "cask install gu-strap"
Error: Unknown command: cask install gu-strap
➜  brew cask install gu-strap
Updating Homebrew...
^C^C
```
Credit to @philmcmahon, just upstreaming.
> Remove quotes around custom brew command

- bin/strap.sh
Previously this check would also match if the user was part of another group that included the word admin (e.g. _lpadmin). Now limit the check to only look for the whole word 'admin'.
> Improve the check for whether the user is in the admin group

- script/cibuild
- web/app.rb
Previously they were not being set for non-HTML files.
> Ensure X-Frame-Options are set consistently

- bin/strap.sh
This works on 10.13 and above and fails gracefully on older versions.
While I'm here: don't require bumping on each macOS (there doesn't seem to be code changes needed any more.)
Companion to https://github.com/Homebrew/install/pull/235
> Simplify CLT installation.

- bin/strap.sh
I've tested this on both Mojave and Catalina. Strap's current `master` fails if you have long running processes as the current askpass binary throws a permission denied error. There doesn't seem to be any reason to have it owned by root or to set the sticky bit. I've removed those two things to great avail.
> sudo askpass: owned by user, no sticky bit

- web/app.rb
To edit workflow files using OAuth the `workflow` scope is necessary. This restriction was put in place to prevent nefarious OAuth apps from being able to push workflow files (which could cost users money or compromise secrets).
Developers using `strap` to boostrap their environments will however want the ability to edit workflow files and as such we should request the scope here.
> Add workflow to requested oauth scopes

- .github/workflows/tests.yml
This was only needed on older versions of macOS.
> workflows/tests: remove unneeded `pkgutil --forget`.

- web/app.rb
There is a request to be able to use strap's token to login to GitHub Package Registry.
> Add GPR support to GITHUB_TOKEN

- web/app.rb
This makes it possible to use this same token for working with [GitHub's cli](https://github.com/cli/cli).
> This adds permissions for gh cli

- .github/workflows/tests.yml
There's some existing taps messing with `brew update` runs.
> tests: cleanup Homebrew.

- .github/workflows/tests.yml
No longer required as-of https://github.com/Homebrew/brew/pull/9189.
> workflows/tests: remove Big Sur workaround.

- web/app.rb
The app itself doesn't actually `POST` to the omniauth checkpoint, so attempting to fetch `strap.sh` just falls back on the debug response that prints the route that was being fetched.
> Revert "Use POST for OmniAuth."

- .github/workflows/tests.yml
- web/app.rb
- Let VS Code auto-format the YAML.
- use `brew install --formula` and `brew install --cask` instead. These flags aren't needed but let's use them for explicitness/testing.
- Remove documentation reference to `brew cask install`.
> Handle `brew cask install` deprecation

- web/app.rb
An environment I'm deploying to involves some auth stuff that requires this.
> Omniauth: allow configuring full_host

- .github/workflows/tests.yml
- bin/strap.sh
When rerunning Strap and Homebrew was already installed the `HOMEBREW_REPOSITORY` could be unset causing failures.
Also, add a CI test to verify this case.
> strap.sh: handle rerunning Strap.

- bin/strap.sh
This handles e.g. https://github.com/MikeMcQuaid/dotfiles/commit/16bb28608c761293061a03eef666b09ffb611ff7 so that cross-platform credential handling can be done.
> bin/strap.sh: make credential handling more generic.

- web/app.rb
For some reason this needs to be a no-op when using OMNIAUTH_FULL_HOST.
> web/app: tweak omniauth request validation.

- bin/strap.sh
Certain macOS AV tools that might come pre-installed in an enterprise environment may install themselves into `/usr/local` and may intercept calls to `chown` to avoid having their ownership changed. Unfortunately, this causes the Homebrew install step of strap.sh to fail on such machines with these AV tools installed.
It seems like a recursive chown isn't really necessary in this case, especially since on a fresh machine, the directories would have just been created and not have anything in them yet. Additionally, I don't think the Homebrew installer uses a recursive `chown` for these directories. If there's a case I'm not thinking about here and the recursive `chown` is important, I would maybe advocate for using `-f` instead, to avoid permissions errors from tanking the `chown`
> Make /usr/local/* chowns non-recursive

- .github/workflows/tests.yml
This can be done with a raw `GITHUB_TOKEN`.
> workflows/tests: fix ghcr token.

- bin/strap.sh
Allow cross-platform Git credential wrapper scripts (e.g. https://github.com/MikeMcQuaid/dotfiles/blob/master/bin/git-credential-dotfiles) to play nice with Strap.
> strap.sh: handle credential wrapper scripts.

- bin/strap.sh
- script/cibuild
If `sudo` is setup to use `pam_tid` for TouchID: don't prompt for a password.
Checkout https://github.com/MikeMcQuaid/dotfiles/blob/master/bin/touchid-enable-pam-sudo if you're interested in a script to enable TouchID for `sudo`.
> strap: better handle TouchID.

- .github/workflows/tests.yml
- Dockerfile
workflows/tests: fix Heroku.
Need to manually push images to Heroku now.
While we're here:
- use macOS 12 for CI.
- always output Xcode versions to make it easier to fix them up in future
- Always login and tag Docker images but only push for `master`
- Run `Dockerfile` as a non-root user
> workflows/tests: fix Heroku.

- README.md
- bin/strap.sh
- script/style
If the necessary PAM module exists and the configuration file is in the
expected format: enable the TouchID PAM module.
> Enable `sudo` using TouchID

- .github/workflows/tests.yml
It has `brew` in the `PATH` for now and use `Homebrew/actions/setup-homebrew` to handle when it does not.
> Use GitHub Actions Ubuntu 22.04

- web/app.rb
Given currently deployment methods, this is unnecessary and harms attempts to do e.g. readiness probes over HTTP.
> app: don't attempt https redirects.

- .shellcheckrc
- script/style
- add `.shellcheckrc` file for consistent behaviour
- remove accidentally committed `set -x`
- autocorrect using `shellcheck` too
- make `shfmt` output errors properly
- use non-deprecated `rubocop` argument
> More style fixes

- .github/workflows/tests.yml
GitHub Actions overrides this by default.
> workflows/tests: install from Homebrew API.

- script/style
This was missing a `pam_tid` check.
While we're here:
- improve the language
- fix an old `script/cibuild` reference
- improve the formatting
> script/style: fix regex.

- web/app.rb
The previous one was incorrect, seemingly.
I'm aware GitHub secret detection may mean this can no longer be committed any more. Let's find out!
> web/app: add new development client secret.

- .github/workflows/tests.yml
Otherwise we don't push to Docker Hub on `main` pushes.
> workflows/tests: fix Docker Hub default branch reference.

- .github/dependabot.yml
- .github/workflows/codeql.yml
- .github/workflows/tests.yml
- Get Dependabot to check for GitHub Actions updates
- Check for Dependabot updates at different times
- Group Dependabot updates where possible
- Switch GitHub Actions to use tags where possible
> Improve GitHub Actions configuration

- .github/workflows/tests.yml
- script/bootstrap
- script/server
- script/style
- script/tests
- avoid `run: |` in GitHub Actions where possible
- use `set -euo pipefail` more often in GitHub Actions and scripts
- use `set -x` too in `script/tests` to make failures more obvious
> Cleanup workflows and scripts

- Gemfile
- Gemfile.lock
- Guardfile
- README.md
- script/server
- script/tests
- web/puma.rb
- web/unicorn.rb
Puma is actually actively maintained so is a better fit.
While we're here:
- fix `script/tests` to kill Puma properly on exit and reduce the (excessive) sleep time
- note that Puma is used in the README
- fix up other Unicorn references
> Use Puma instead of Unicorn

- web/views/root.erb
The sponsorship drive has been a dismal failure so point people to Workbrew instead (as it's at the stage that people may actually find it interesting and useful).
> web/views/root: note Workbrew.

- web/views/root.erb
To avoid content overlapping with footer.
> web/views/root: add bottom spacer.

- .github/workflows/tests.yml
- Use official Docker actions
- Login to DigitalOcean and push to container registry there
> workflows/tests: improve Docker image build and push.

- .github/workflows/tests.yml
This should help free up more space.
> workflows/tests: garbage collect Docker images before pushing.
